name: first workflow
on:
 push:
  branches:
    -"main"
jobs:
 first-workflow-job:
  name: first job
  runs-on: ubuntu-lastest
  steps:
   -name: run bash command
    run: rcho "first workflow"
    sell: bash