#  Workflow 3: Trigger using repository_dispatch with type build

name: Repository Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: "This is the version for GitHub workflow di"

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
