# name: first workflow

# on:
#   workflow_dispatch:
#     inputs:
#       versionName:
#         required: true
#         description: "This is the version for GitHub workflow"

# jobs:
#   first-workflow-job:
#     name: first job
#     runs-on: ubuntu-latest
#     steps:
#       - name: before checkout action
#         if: startsWith(github.ref, 'refs/heads/feature')
#         run: ls
#         shell: bash

#       - name: checkout code
#         uses: actions/checkout@v3

#       - name: list files after checkout
#         if: github.event.inputs.versionName == 'test'
#         run: ls
#         shell: bash
