name: first workflow

on:
  push:
    branches:
      - "main"
      - "feat/**"

#     paths:
#       - "app/**"
#   pull_request:
#     branches-ignore:
#       - "feat/**"
#     types: [opened, closed]
#   workflow_dispatch:

jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    container:
      image: node:14.16
    steps:
      - name: check node version
        run: node -v

      - name: before checkout action
        run: ls
        shell: bash

      - name: checkout code
        uses: actions/checkout@v3

      - name: list files after checkout
        run: ls
        shell: bash
