name: first workflow

on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: "this is version for github workflow for gitbuh workflow"

  # push:
  #   branches:
  #     - "main"
  # pull_request:
  #   branches:
  #     - "feature"
  #   types: [opened, closed]

jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: before checkout action
        run: ls
        shell: bash

      - name: checkout code
        uses: actions/checkout@v3

      - name: list files after checkout
        run: ls
        shell: bash
