name: first workflow
on:
  push:
    branches:
      - "main"

jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: before checkout action
        run: ls
        shell: bash
      
      - name: checkout code
        uses: actions/checkout@v3

      - name: list files after checkout
        run: ls
        shell: bash
